version: "4.32"

services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123123
  db:
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_DB: postgresql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123
    ports:
      - "5432:5432"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


